-- Add UUID columns to clients and users tables for external identification
-- Note: For PostgreSQL use gen_random_uuid(), for H2 use RANDOM_UUID()
-- This migration assumes new records will have UUIDs generated by JPA @PrePersist
ALTER TABLE clients ADD COLUMN uuid UUID;
CREATE UNIQUE INDEX idx_clients_uuid ON clients(uuid);

ALTER TABLE users ADD COLUMN uuid UUID;
CREATE UNIQUE INDEX idx_users_uuid ON users(uuid);

-- Generate UUIDs for existing records
-- PostgreSQL: gen_random_uuid()
-- H2: RANDOM_UUID()
-- Note: If you have existing data, you may need to run database-specific updates
-- For PostgreSQL: UPDATE clients SET uuid = gen_random_uuid() WHERE uuid IS NULL;
-- For H2: UPDATE clients SET uuid = RANDOM_UUID() WHERE uuid IS NULL;
-- UPDATE users SET uuid = gen_random_uuid() WHERE uuid IS NULL; -- PostgreSQL
-- UPDATE users SET uuid = RANDOM_UUID() WHERE uuid IS NULL; -- H2

-- Make UUID columns NOT NULL after populating
-- Note: Run the UPDATE statements above first if you have existing data
ALTER TABLE clients ALTER COLUMN uuid SET NOT NULL;
ALTER TABLE users ALTER COLUMN uuid SET NOT NULL;

